### ISSUE TITLE
LargeFileUploader returns 504 on byte-range upload method

### ISSUE THREAD

**Issue by averabaqsncr** [emcvipr/ecs-object-client-java#1]
I'm getting a 504 http error code (The target server failed to respond) every time I use the byte-range update feature (MTU is ok), but only if the content length of the object is set as part of the metadata, otherwise the file is uploaded successfully.

Below is the line of code that is causing the issue:

LargeFileUploader.java(174): s3Client.putObject(request);

For testing this I'm using the ECS test drive with a self-created account. See details below:

#################################
endpoints=https://object.ecstestdrive.com
accessKey={accesskey}
secretKey={secretkey}
#################################

Snippet code that causes the issue:
#################################
S3ObjectMetadata objectMetadata = new S3ObjectMetadata();
// this makes the uploader to fail with 504
//objectMetadata.setContentLength(contentLength);

LargeFileUploader uploader = new LargeFileUploader(_client, bucketKey, key, new File(tempFile));
uploader.setPartSize(_partSize);
uploader.setThreads(8);
uploader.setObjectMetadata(objectMetadata);
uploader.doByteRangeUpload();

**Comment by twincitiesguy** [comment]
Fixed in 2.0 release
